a = input('digite algo = ')
print('tipo primitivo do valor é ', type(a))
print('esta em alfabeto ?', a.isalpha())
print('tem espaços ?', a.isspace())
print('tem valor numerico ?', a.isnumeric())
print('esta em maiusculo ?', a.isupper())
print('esta em minusculo ?', a.islower())
print('são alfanumericos ?', a.isalnum())
print('esta em decimal ?', a.isdecimal())
print('esta em digitos ?', a.isdigit())
